Fix/Router 버그 문제 해결
prgrms-fe-devcourse/FEDC2_TTaBong_Dali pull request #42
Opened 2022-06-14 18:59 UTC by MayOwall

### 📌 설명

BottomBar를 포함한 `<Link>`를 사용하는 컴포넌트들이 정상적으로 랜더링 될 수 있도록 함.

<img width="1147" alt="image" src="https://user-images.githubusercontent.com/97934878/173667003-9e368a00-0dd3-4a11-987c-4d196cee931a.png">

### 🎨 구현 내용

**`<Link>`를 사용하는 모든 컴포넌트는 기본적으로 `<Router>`태그로 감싸줘야 합니다!**

<img width="414" alt="image" src="https://user-images.githubusercontent.com/97934878/173667872-fc899743-2408-43e0-941c-b606d2493775.png">

cf.
Router는  `import { BrowserRouter as Router } from 'react-router-dom'`으로 하는 것 잊지말기~~

### ✅ 중점적으로 봐줬으면 하는 부분

### 🚀 연관된 이슈
close #41

2022-06-14 19:00 UTC, Steadystudy approved these changes
오호 Route 뿐만 아니라 Link도 Router로 감싸야 하는 군요!

2022-06-14 19:13 UTC, devBuzz142 requested changes
<img width="474" alt="image" src="https://user-images.githubusercontent.com/19660039/173670016-52f86d26-7ea3-4103-a1be-c418449a9923.png">

컴포넌트 index.jsx 파일들은 결국 라우터 안의 App에서 호출되는 반면,

스토리북 컴포넌트들은 그렇지 않아서 문제가 발생하는 것 같네요.

원본 컴포넌트에 라우터를 추가하는 것보단 스토리북 컴포넌트에 추가하는 것이 나을 것 같아요.

2022-06-15 05:24 UTC, MayOwall commented
> <img alt="image" width="474" src="https://user-images.githubusercontent.com/19660039/173670016-52f86d26-7ea3-4103-a1be-c418449a9923.png">
> 
> 컴포넌트 index.jsx 파일들은 결국 라우터 안의 App에서 호출되는 반면,
> 
> 스토리북 컴포넌트들은 그렇지 않아서 문제가 발생하는 것 같네요.
> 
> 원본 컴포넌트에 라우터를 추가하는 것보단 스토리북 컴포넌트에 추가하는 것이 나을 것 같아요.

@devBuzz142 

수정 완료했습니다. 다시 확인 부탁드려요!!

2022-06-15 06:02 UTC, devBuzz142 approved these changes
더 찾아보니까 story-react-router 라이브러리를 사용해서 해결하는 방법도 있더군요. 근데 지금은 메인 페이지 구현이 우선이니까 이건 이슈로만 남겨둘게요.
고생하셨습니다.

2022-06-15 06:03 UTC, merged